

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://gaganshuyadav16:MmL4N8GV2dF15o34@cluster0.n6m6xvh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDBForMyFirstSringboot
      auto-index-creation: true
  main:
    allow-circular-references: true
  application:
    name: myfirstsringboot

server:
  port: 8888
  servlet:
    context-path: /

logging:
  level:
    com:
      gagansp1:
        myfirstsringboot: TRACE

#logging:
#  level:
#    root: OFF
#

#logging:
#  level:
#    com:
#      gagansp1:
#        myfirstsringboot: OFF
